#CategoryDetailView {
    background-color: transparent;
    border: none;
}

#TrackView {
    background-color: transparent;
    border: none;
}

#TitleLabel {
    color: rgba(25,2,12,1);
    background: transparent;
    border: none;
}

#TextLabel {
    color: rgba(25,2,12,0.5);
    background: transparent;
    border: none;
}

#NumLabel {
    color: rgba(25,2,12, 0.5);
    background: transparent;
    border: none;
}

